// --- ACTIONS TYPE REGION
export const RESET_CURRENT_FESTIVAL = 'RESET_CURRENT_FESTIVAL';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const STORE_FESTIVALS = 'STORE_FESTIVALS';
export const STORE_CURRENT_FESTIVAL = 'STORE_CURRENT_FESTIVAL';
export const STORE_CURRENT_FESTIVAL_ID = 'STORE_CURRENT_FESTIVAL_ID';
// --- ACTIONS TYPE REGION END
