// --- ACTIONS TYPE REGION
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const STORE_FESTIVALS = 'STORE_FESTIVALS';
export const STORE_CURRENT_FESTIVAL = 'STORE_CURRENT_FESTIVAL';
// --- ACTIONS TYPE REGION END
